export const URLS = {
    version: '/version',
    login: '/login',
    //users
    userCreate: '/user/create',
    userEdit: '/user/edit',
    userDisabled: '/user/disabled/:id',
    userActive: '/user/active/:id',
    userPasswordChange: '/user/password/change',
    userPasswordRecovery: '/user/password/recovery',
    getAllUser: '/user/getalluser',
    getOneUser: '/user/getoneuser/:id',
    validateUser: '/user/validate',
    //ruta para publicaciones
    createPublication: '/publication/create',
    getPublications: '/publication/getpublications',
    getAllPublications: '/publication/getallpublications',
    disabledPublications: '/publication/disabledpublications/:id',
    activePublications: '/publication/activepublications/:id',
    editPublications: '/publication/editpublications',
    getOnePublications: '/publication/getonepublications/:id',
    getOneTokenPublications: '/publication/getonetokenpublications/:id',
    deleteImagen: '/publication/deleteimagen/:id',
    //ruta para las categorias
    createCategory: '/category/create',
    getAllCategories: '/category/getallcategories',
    getOneCategory: '/category/getonecategory/:id',
    editCategory: '/category/editcategory',
    daleteCategory: '/category/daletecategory/:id',
    getListCategories: '/category/getlistcategories',
    activeCategory: '/category/activecategory/:id',
    //ruta para los roles
    createRole: '/role/create',
    getAllRoles: '/role/getallroles',
    getListRoles: '/role/getlistroles',
    getOneRole: '/role/getonerole/:id',
    editRole: '/role/editrole',
    deleteRole: '/role/deleterole/:id',
    activeRole: '/role/activerole/:id',
    //ruta para galeri de videos
    createVideo: '/video/create',
    getAllVideos: '/video/getallvideos',
    getListVedios: '/video/getlistvideos',
    getOneVideo: '/video/getonevideo/:id',
    editvideo: '/video/editvideo',
    disabledVideo: '/video/disabled/:id',
    deleteVideo: '/video/delete/:id',
    activeVideo: '/video/active/:id',
}